version: "3.9"
services:
    postgres:
      image: postgres:15.1-alpine
      restart: unless-stopped
      network_mode: "host"
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
      ports:
        - "5432:5432"
      volumes:
        - './.docker/postgres/:/docker-entrypoint-initdb.d/'
      expose:
        - 5432

networks:
  default:
    name: postgre-service_default
        